### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by lazaropj** [alvarowolfx/ng-pokedex#1]
Hi,

You forgot of commit the package.json file.

**Comment by alvarowolfx** [comment]
The project didn't need a package.json, you could see the README for instructions on how to run the project. You just have to install `browser-sync` globally with `npm` and run the `serve.sh` script.

But I will send a update to start the project using `npm start`.

**Comment by alvarowolfx** [comment]
@lazaropj I changed the project structure and add the `package.json` file. You can even see it running on Github Pages now. http://alvarowolfx.github.io/ng-pokedex/

🚀
